CREATE TABLE IF NOT EXISTS `user` (
`id` INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
`username` VARCHAR(30) NOT NULL,
`email` VARCHAR(50) NOT NULL,
`password` text NOT NULL,
`reg_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)  ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `newc` (
`idnewc` INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
`username` VARCHAR(30) NOT NULL,
`newcode` VARCHAR(30) NOT NULL,
`newnamed` VARCHAR(30) NOT NULL,
`reg_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)  ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `joinc` (
`idjoinc` INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
`username` VARCHAR(30) NOT NULL,
`joincode` VARCHAR(30) NOT NULL,
`ownerd` VARCHAR(30) NOT NULL,
`joinname` VARCHAR(30) NOT NULL,
`reg_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)  ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `approv` (
`idjoincv` INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
`usernamev` VARCHAR(30) NOT NULL,
`joincodev` VARCHAR(30) NOT NULL,
`ownerdv` VARCHAR(30) NOT NULL,
`joinnamev` VARCHAR(30) NOT NULL,
`reg_datev` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)  ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `images` (
    `idimg` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` text ,
    `size` int(50) ,
    `type` text ,
    `path` text ,
    `title` text NOT NULL,
    `description` text NOT NULL,
    `usrnam` text NOT NULL,
    `cod` text NOT NULL,
    `nam` text NOT NULL,
    `uploaded_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `comments` (
    `idcom` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `comment` text,
    `user` text NOT NULL,
    `postid` int(11) ,
    `timecom` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



CREATE TABLE IF NOT EXISTS `teacher` (
`idnewtea` INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
`usernamet` VARCHAR(30) NOT NULL,
`newcodet` VARCHAR(30) NOT NULL,
`newnamedt` VARCHAR(30) NOT NULL,
`ownert` VARCHAR(30) NOT NULL,
`reg_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)  ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;